name: Build and Deploy Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run once a week to check for content updates
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup environment variables
      run: |
        echo "POST_URL=${{ secrets.POST_URL }}" >> $GITHUB_ENV
        echo "SERVICE_URL=${{ secrets.SERVICE_URL }}" >> $GITHUB_ENV
        echo "PROJECT_URL=${{ secrets.PROJECT_URL }}" >> $GITHUB_ENV
        echo "CONTACT_URL=${{ secrets.CONTACT_URL }}" >> $GITHUB_ENV
        echo "GOOGLE_DRIVE_FOLDER_URL=${{ secrets.GOOGLE_DRIVE_FOLDER_URL }}" >> $GITHUB_ENV
        echo "SITE_TITLE=${{ secrets.SITE_TITLE }}" >> $GITHUB_ENV
        echo "SITE_DESCRIPTION=${{ secrets.SITE_DESCRIPTION }}" >> $GITHUB_ENV
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

    - name: Fetch content from Google Sheets
      run: npm run fetch-content

    - name: Build Tailwind CSS
      run: npx tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --minify

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public